/* Gerado por scripts/baixar-imagens.cjs em 2026-08-14T01:19:07.793Z.
   Não edite à mão: rode o script de novo.
   Mapa id do produto -> arquivo local em assets/produtos/.
   O que não estiver aqui cai na ilustração vetorial da garrafa (bottles.js). */
window.PRODUCT_IMAGES = {
  "wh-2": "assets/produtos/whisky-ballantines-finest-1l.webp",
  "wh-4": "assets/produtos/whisky-chivas-regal-12-anos-1l.webp",
  "wh-7": "assets/produtos/whisky-jack-daniels-fire-1l.webp",
  "wh-8": "assets/produtos/whisky-jack-daniels-old-no-7-1l.webp",
  "wh-9": "assets/produtos/whisky-jack-daniels-honey-1l.webp",
  "wh-10": "assets/produtos/whisky-jim-beam-bourbon-1l.webp",
  "wh-11": "assets/produtos/whisky-johnnie-walker-black-label-1l.webp",
  "wh-12": "assets/produtos/whisky-johnnie-walker-red-label-1l.webp",
  "wh-14": "assets/produtos/whisky-passport-1l.webp",
  "wh-15": "assets/produtos/whisky-white-horse-1l.webp",
  "vk-1": "assets/produtos/vodka-absolut-1l.webp",
  "vk-2": "assets/produtos/vodka-ciroc-original-750ml.webp",
  "vk-3": "assets/produtos/vodka-grey-goose-750ml.webp",
  "vk-5": "assets/produtos/vodka-orloff-1l.webp",
  "vk-9": "assets/produtos/vodka-smirnoff-21-998ml.webp",
  "gn-1": "assets/produtos/gin-gordons-london-dry-750ml.webp",
  "gn-4": "assets/produtos/gin-seagers-original-1l.webp",
  "gn-5": "assets/produtos/gin-tanqueray-london-dry-750ml.webp",
  "gn-6": "assets/produtos/tequila-jose-cuervo-reposado-750ml.webp",
  "gn-7": "assets/produtos/tequila-jose-cuervo-silver-750ml.webp",
  "rm-1": "assets/produtos/rum-bacardi-big-apple-700ml.webp",
  "rm-2": "assets/produtos/rum-bacardi-carta-blanca-superior-980ml.webp",
  "rm-3": "assets/produtos/rum-bacardi-gold-980ml.webp",
  "rm-5": "assets/produtos/rum-malibu-coconut-750ml.webp",
  "rm-6": "assets/produtos/rum-montilla-carta-cristal-1l.webp",
  "rm-7": "assets/produtos/rum-montilla-carta-ouro-1l.webp",
  "lc-1": "assets/produtos/aperitivo-aperol-spritz-750ml.webp",
  "lc-3": "assets/produtos/licor-43-chocolate-edition-700ml.webp",
  "lc-4": "assets/produtos/licor-amarula-cream-750ml.webp",
  "lc-5": "assets/produtos/licor-amaretto-dell-orso-700ml.webp",
  "lc-6": "assets/produtos/licor-don-luiz-doce-de-leite-750ml.webp",
  "lc-7": "assets/produtos/licor-cointreau-liqueur-700ml.webp",
  "lc-8": "assets/produtos/licor-jagermeister-herb-700ml.webp",
  "cc-1": "assets/produtos/cachaca-51-pirassununga-965ml.webp",
  "cc-2": "assets/produtos/cachaca-velho-barreiro-910ml.webp",
  "cc-3": "assets/produtos/cachaca-ypioca-brasilizar-ouro-965ml.webp",
  "cc-6": "assets/produtos/conhaque-domecq-1l.webp",
  "cc-7": "assets/produtos/conhaque-dreher-900ml.webp",
  "cc-8": "assets/produtos/conhaque-presidente-900ml.webp",
  "vb-1": "assets/produtos/brasilberg-original-aperitivo-920ml.webp",
  "vb-2": "assets/produtos/bitter-campari-red-998ml.webp",
  "vb-3": "assets/produtos/vermouth-martini-bianco-750ml.webp",
  "vb-4": "assets/produtos/vermouth-martini-extra-dry-750ml.webp",
  "vb-5": "assets/produtos/vermouth-martini-rosato-750ml.webp",
  "vb-6": "assets/produtos/vermouth-martini-rosso-750ml.webp"
};
